# Test CI/CD Pipeline Script (PowerShell)
# This script creates a test PR to verify your CI/CD pipeline is working

Write-Host "🚀 SmartCrop - CI/CD Pipeline Test Script" -ForegroundColor Green
Write-Host "=============================================" -ForegroundColor Green
Write-Host ""

# Check if we're in the right directory
if (-not (Test-Path "backend") -and -not (Test-Path "package.json")) {
    Write-Host "❌ Error: Please run this script from the project root" -ForegroundColor Red
    exit 1
}

# Check if git is initialized
if (-not (Test-Path ".git")) {
    Write-Host "❌ Error: Not a git repository" -ForegroundColor Red
    exit 1
}

# Get current branch
$currentBranch = git branch --show-current
Write-Host "📍 Current branch: $currentBranch" -ForegroundColor Yellow
Write-Host ""

# Switch to develop
Write-Host "⏳ Switching to develop branch..." -ForegroundColor Cyan
try {
    git checkout develop 2>$null
} catch {
    Write-Host "❌ Error: develop branch doesn't exist. Creating it..." -ForegroundColor Red
    git checkout -b develop
    git push origin develop
}

# Pull latest
Write-Host "⏳ Pulling latest changes..." -ForegroundColor Cyan
git pull origin develop

# Create test branch
$timestamp = [int][double]::Parse((Get-Date -UFormat %s))
$testBranch = "test/ci-pipeline-$timestamp"
Write-Host "🌿 Creating test branch: $testBranch" -ForegroundColor Yellow
git checkout -b $testBranch

# Make a small change
$date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
Add-Content -Path "README.md" -Value "`n<!-- CI/CD Test - $date -->"

# Commit change
Write-Host "💾 Committing test change..." -ForegroundColor Cyan
git add README.md
git commit -m "test(ci): verify CI/CD pipeline functionality

This is an automated test commit to verify the GitHub Actions CI/CD pipeline.

- Tests lint checks
- Tests unit tests
- Tests build process
- Tests security scans

This commit can be safely reverted or merged."

# Push to remote
Write-Host "📤 Pushing to remote..." -ForegroundColor Cyan
git push origin $testBranch

Write-Host ""
Write-Host "✅ Test branch created and pushed!" -ForegroundColor Green
Write-Host ""
Write-Host "====================================" -ForegroundColor Green
Write-Host "📋 Next Steps:" -ForegroundColor Green
Write-Host "====================================" -ForegroundColor Green
Write-Host ""
Write-Host "1. Go to your GitHub repository:"
Write-Host "   https://github.com/yellowflowersorganics-star/smartcrop" -ForegroundColor Cyan
Write-Host ""
Write-Host "2. Click 'Pull requests' tab"
Write-Host ""
Write-Host "3. Click 'New pull request'"
Write-Host ""
Write-Host "4. Select:"
Write-Host "   Base: develop ← Compare: $testBranch" -ForegroundColor Yellow
Write-Host ""
Write-Host "5. Click 'Create pull request'"
Write-Host ""
Write-Host "6. Watch the Actions tab to see CI/CD run:"
Write-Host "   https://github.com/yellowflowersorganics-star/smartcrop/actions" -ForegroundColor Cyan
Write-Host ""
Write-Host "7. Once checks pass:"
Write-Host "   - Review the PR"
Write-Host "   - Merge it (or close if just testing)"
Write-Host "   - Delete the test branch"
Write-Host ""
Write-Host "💡 Tip: If all checks are green, your CI/CD is working!" -ForegroundColor Yellow
Write-Host ""

# Check if GitHub CLI is available
if (Get-Command gh -ErrorAction SilentlyContinue) {
    Write-Host "🤖 GitHub CLI detected!" -ForegroundColor Yellow
    $response = Read-Host "Do you want to create the PR automatically? (y/n)"
    
    if ($response -eq 'y' -or $response -eq 'Y') {
        Write-Host "⏳ Creating pull request..." -ForegroundColor Cyan
        
        $prBody = "This is an automated test PR to verify the GitHub Actions CI/CD pipeline is working correctly.

## What This Tests

- Code linting (ESLint)
- Unit tests (Jest/Vitest)
- Docker builds
- Security scanning (Trivy)
- npm audit

## Expected Result

All status checks should pass

## After Testing

- If all checks pass: Merge or close this PR
- If checks fail: Review the logs and fix issues
- Delete the test branch after merging/closing

---

*Generated by test-cicd.ps1 script*"
        
        gh pr create `
            --base develop `
            --head $testBranch `
            --title "test(ci): Verify CI/CD Pipeline" `
            --body $prBody
        
        Write-Host "✅ Pull request created!" -ForegroundColor Green
        Write-Host ""
        Write-Host "Opening PR in browser..." -ForegroundColor Cyan
        gh pr view --web
    }
} else {
    Write-Host "💡 Install GitHub CLI (gh) for automatic PR creation" -ForegroundColor Yellow
    Write-Host "   https://cli.github.com/"
}

Write-Host ""
Write-Host "🎉 CI/CD test setup complete!" -ForegroundColor Green

