#!/bin/bash

# Test CI/CD Pipeline Script
# This script creates a test PR to verify your CI/CD pipeline is working

set -e

echo "🚀 SmartCrop - CI/CD Pipeline Test Script"
echo "============================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if we're in the right directory
if [ ! -f "package.json" ] && [ ! -d "backend" ]; then
    echo -e "${RED}❌ Error: Please run this script from the project root${NC}"
    exit 1
fi

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo -e "${RED}❌ Error: Not a git repository${NC}"
    exit 1
fi

# Get current branch
CURRENT_BRANCH=$(git branch --show-current)
echo -e "${YELLOW}📍 Current branch: ${CURRENT_BRANCH}${NC}"
echo ""

# Switch to develop
echo "⏳ Switching to develop branch..."
git checkout develop 2>/dev/null || {
    echo -e "${RED}❌ Error: develop branch doesn't exist. Creating it...${NC}"
    git checkout -b develop
    git push origin develop
}

# Pull latest
echo "⏳ Pulling latest changes..."
git pull origin develop

# Create test branch
TEST_BRANCH="test/ci-pipeline-$(date +%s)"
echo -e "${YELLOW}🌿 Creating test branch: ${TEST_BRANCH}${NC}"
git checkout -b "$TEST_BRANCH"

# Make a small change
echo "" >> README.md
echo "<!-- CI/CD Test - $(date) -->" >> README.md

# Commit change
echo "💾 Committing test change..."
git add README.md
git commit -m "test(ci): verify CI/CD pipeline functionality

This is an automated test commit to verify the GitHub Actions CI/CD pipeline.

- Tests lint checks
- Tests unit tests
- Tests build process
- Tests security scans

This commit can be safely reverted or merged."

# Push to remote
echo "📤 Pushing to remote..."
git push origin "$TEST_BRANCH"

echo ""
echo -e "${GREEN}✅ Test branch created and pushed!${NC}"
echo ""
echo "===================================="
echo "📋 Next Steps:"
echo "===================================="
echo ""
echo "1. Go to your GitHub repository:"
echo "   https://github.com/yellowflowersorganics-star/smartcrop"
echo ""
echo "2. Click 'Pull requests' tab"
echo ""
echo "3. Click 'New pull request'"
echo ""
echo "4. Select:"
echo "   Base: develop ← Compare: $TEST_BRANCH"
echo ""
echo "5. Click 'Create pull request'"
echo ""
echo "6. Watch the Actions tab to see CI/CD run:"
echo "   https://github.com/yellowflowersorganics-star/smartcrop/actions"
echo ""
echo "7. Once checks pass:"
echo "   - Review the PR"
echo "   - Merge it (or close if just testing)"
echo "   - Delete the test branch"
echo ""
echo -e "${YELLOW}💡 Tip: If all checks are green, your CI/CD is working!${NC}"
echo ""

# Ask if user wants to create PR via GitHub CLI (if available)
if command -v gh &> /dev/null; then
    echo -e "${YELLOW}🤖 GitHub CLI detected!${NC}"
    read -p "Do you want to create the PR automatically? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "⏳ Creating pull request..."
        gh pr create \
            --base develop \
            --head "$TEST_BRANCH" \
            --title "test(ci): Verify CI/CD Pipeline" \
            --body "This is an automated test PR to verify the GitHub Actions CI/CD pipeline is working correctly.

## What This Tests

- ✅ Code linting (ESLint)
- ✅ Unit tests (Jest/Vitest)
- ✅ Docker builds
- ✅ Security scanning (Trivy)
- ✅ npm audit

## Expected Result

All status checks should pass ✅

## After Testing

- If all checks pass: Merge or close this PR
- If checks fail: Review the logs and fix issues
- Delete the test branch after merging/closing

---

*Generated by test-cicd.sh script*"
        
        echo -e "${GREEN}✅ Pull request created!${NC}"
        echo ""
        echo "View PR: $(gh pr view --web 2>/dev/null || echo 'Check GitHub')"
    fi
else
    echo -e "${YELLOW}💡 Install GitHub CLI (gh) for automatic PR creation${NC}"
    echo "   https://cli.github.com/"
fi

echo ""
echo -e "${GREEN}🎉 CI/CD test setup complete!${NC}"

